# analysis_heat_index.sub -- Calculate heat index

executable = /usr/bin/python3
arguments = /mnt/data/use_cases/code/task_heat_index.py $(file) /mnt/data/use_cases/analysis

# Logging
log    = /mnt/data/use_cases/logs/analysis_HI_$(Process).log
output = /mnt/data/use_cases/logs/analysis_HI_$(Process).out
error  = /mnt/data/use_cases/logs/analysis_HI_$(Process).err

# Resources
request_cpus   = 1
request_memory = 2G

queue file matching /mnt/data/use_cases/clean/*.csv
