# expand_data.sub -- Expand data to about 10GB to simulate big data

executable = /usr/bin/python3
arguments = /mnt/data/use_cases/code/expand_data.py /mnt/data/use_cases/clean_weather.csv /mnt/data/use_cases/expanded_weather.csv

# Logging
output = /mnt/data/use_cases/logs/expand_data.out
error  = /mnt/data/use_cases/logs/expand_data.err
log    = /mnt/data/use_cases/logs/expand_data.log

# Resources
request_cpus   = 1
request_memory = 6G

queue
